PREFIX xsi: <http://www.w3.org/2001/XMLSchema-instance#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX fx: <http://sparql.xyz/facade-x/ns/> 
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xml: <http://www.w3.org/XML/1998/namespace#>
PREFIX haObjId: <https://data.hetarchief.be/id/object/>
PREFIX premisowl: <http://www.loc.gov/premis/rdf/v3/>
PREFIX premis: <http://www.loc.gov/premis/v3#>
PREFIX edtf: <http://id.loc.gov/datatypes/edtf/>
PREFIX schema: <https://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mods: <http://www.loc.gov/mods/v3>

CONSTRUCT
{
    ?ie a premisowl:IntellectualEntity;
        dct:title ?title ;
}
WHERE
{ 
    SERVICE <x-sparql-anything:location={{ bag_path }}/data/metadata/descriptive/mods.xml> {
        [] a fx:root;

        ?mods_1 [
            a mods:titleInfo;
            ?mods_title_info [
                a mods:title;
                    rdf:_1 ?title
            ];
        ];
        ?mods_2 [
            a mods:identifier;
                rdf:_1 ?identifier
            ];
        ].


        BIND(iri(concat(str(haObjId:), ?id)) AS ?ie)
    }
}

